apiVersion: v1
kind: Service
metadata:
  name: devopsapp-service
spec:
  type: LoadBalancer   # 🔥 PUBLIC ACCESS
  selector:
    app: devopsapp
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: nginx   # 🔁 CHANGE IMAGE HERE
        ports:
        - containerPort: 80
