apiVersion: v1
kind: Service
metadata:
  name: devopsapp-service
spec:
  type: NodePort
  selector:
    app: devopsapp
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      # ❌ Removed nodePort to avoid conflict
      # Kubernetes will auto-assign a free port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: image_name   # 🔁 replace with your actual image
        ports:
        - containerPort: 8080
